### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by bruskowski** [zehfernandes/screeener#1]
Got the following error message when trying to execute the app on macOS Sierra 10.12.5
Nice idea, though.

```
Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from Error: Command failed: osascript -l JavaScript '/Applications/Screeener.app/Contents/Resources/app/lib/keynoteRobot.js' '{"category":"default","images":[{"height":753,"width":1204,"x":350,"y":130}],"mockup":{"height":1080,"path":"/Applications/Screeener.app/Contents/Resources/app/app/assets/mockups/mockup-desktop.png","width":1920,"x":0,"y":0},"name":"desktop"}' '["/Users/strichpunkt/Desktop/test-1x.png"]'
"---------------BeforeNormalize"
[[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":130,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-623,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-1376,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-1752.5,"width":1204}]]
"---------------LastFullObject"
[[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-1752.5,"width":1204}]]
"------SlideTree"
[[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":130,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-623,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-1376,"width":1204}],[{"path":"/Users/strichpunkt/Desktop/test-1x.png","x":350,"y":-1752.5,"width":1204}]]
/Applications/Screeener.app/Contents/Resources/app/lib/keynoteRobot.js:1270:1299: execution error: Error on line 57: Error: Objekt kann nicht gefunden werden. (-1728)

    at Object.showErrorBox (/Applications/Screeener.app/Contents/Resources/electron.asar/browser/api/dialog.js:247:36)
    at /Applications/Screeener.app/Contents/Resources/app/lib/jxaBridge.js:14:16
    at ChildProcess.exithandler (child_process.js:230:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

**Comment by zehfernandes** [comment]
Hi @richardbruskowski 

I found the bug. It's because I hard code a template name "White" in the English language [here](https://github.com/zehfernandes/screeener/blob/master/lib/keynoteRobot.js#L50)
I will fix in next version. Thanks for reporting.

But if you want to use the app right now, you need to change the keynote language to English in `File > Advanced > Language & Region` and everything would work fine :)


<img width="596" alt="screen shot 2017-07-11 at 11 16 34 am" src="https://user-images.githubusercontent.com/1891339/28072867-93a97c54-662a-11e7-97c7-5d5b17732eef.png">

**Comment by bruskowski** [comment]
Works like a charm now, without the workaround. Thanks!
